spring.datasource.url=jdbc:mysql://localhost:3306/floricultura?useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=floricultura_dev
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
